# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e98a43309a81452b0f484761bf29592500fe8843786f04dfcb97a94104911d469c7d76038772329341e4b15e508ad4b5f030e139df633bc6575436aaafadbd05

test:
  secret_key_base: 7ce6ddb1196e04cbfdb7a91b7e2317fb362f0ded4f05e6e936f8683dfae47f4b132b82506e2839a33c7d414ab2679ba6291405851cd939d27124d62dac6e70cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
